name: Latest blog post workflow
on:
  workflow_dispatch:
  

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: YOUTUBE
          feed_list: "http://feeds.feedburner.com/Events-netSoPaulo"
          feed_address: "http://feeds.feedburner.com/Events-netSoPaulo"
